### DISCUSSION TITLE
Help for building a tcp proxy in shadow

### DISCUSSION THREAD

**Discussion by lorenzo9uerra** [shadow/shadow#1569] [Q&A] [answered]
Hello!

I'm trying to build a tcp proxy that's working in shadow as part of my thesis, but I'm really struggling with it. It should act like a logger, intercepting all the traffic from the client, saving timestamps and messages before forwarding it to tor.
I'm not able to understand what I should do to make it work in shadow and I'm a bit confused about the managed processes, since I couldn't find anything in the documentation about them.
If you could point me in the right direction it would be awesome.

Thank you in advance

**Comment by robgjansen** [comment, marked as answer]
Are you looking for something that logs all network data, such as in the PCAP format? Shadow has a built-in PCAP logger, and it might be easier to use it to get the data you want rather than rolling your own logger tool.

By default, the PCAP logger is turned off. You need to either turn it on for all hosts like this:
```yaml
...
host_defaults:
  pcap_directory: path/to/your/directory
hosts:
  server:
...
```

or for specific hosts like this:
```yaml
...
hosts:
  server:
    pcap_directory: path/to/your/directory
...
```
