### DISCUSSION TITLE
Users in shadow could not access local nginx server in shadow

### DISCUSSION THREAD

**Discussion by beenhuang** [shadow/shadow#1740] [Q&A] [answered]
I modified the shadow.yaml in the getting_started_basic.md file, as below:

```yaml
general:
  stop_time: 10s

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/local/nginx/sbin/nginx
      start_time: 3s

  client:
    quantity: 3
    network_node_id: 0
    processes:
    - path: /bin/curl
      args: -s server
      start_time: 5s
```

Then, Users in shadow could not access the local nginx server in shadow, and I have confirmed that the Nginx is working properly. (Enter `curl -s 127.0.0.1` in the command window and could get the web page information). How should I modify the configuration file？

**Comment by stevenengler** [comment, marked as answer]
Related: #1179

There are a few issues:
1. You're running nginx in daemon mode. In shadow, you should be running programs in their foreground mode.
2. Shadow doesn't support forking processes, so you need to turn off workers in nginx.
3. The default pid file for nginx is `/usr/share/nginx/logs/nginx.pid`, and your user probably doesn't have write access to this directory. You need to choose a path you have access to.
4. Shadow doesn't yet support `sendfile()`, so you need to disable that in nginx.

Your shadow configuration file should look something like:

```yaml
general:
  stop_time: 10s

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/local/nginx/sbin/nginx
      args: -c ../../../nginx.conf -p .
      start_time: 3s
  client:
    network_node_id: 0
    quantity: 3
    processes:
    - path: /bin/curl
      args: -s server
      start_time: 5s
```

and you should have the file `nginx.conf` in the same directory you run shadow from:

```
error_log stderr;

# shadow wants to run nginx in the foreground
daemon off;

# shadow doesn't support fork()
master_process off;
worker_processes 0;

# don't use the system pid file
pid nginx.pid;

events {
  # we're not using any workers, so this is the maximum number
  # of simultaneous connections we can support
  worker_connections 1024;
}

http {
  include             /etc/nginx/mime.types;
  default_type        application/octet-stream;

  # shadow does not support sendfile() nor TCP_NODELAY
  sendfile off;
  tcp_nodelay off;

  access_log off;

  server {
    listen 80;

    location / {
      root /var/www/html;
      index index.nginx-debian.html;
    }
  }
}
```

**Reply by beenhuang** [reply]
I ran nginx with the above configuration in the shadow and showed this errors in the nginx stderr file. How should I do?
(I used Shadow V2.0.0 on Fedora 34)

```
2000/01/01 00:00:03 [alert] 1000#1000: listen() to 0.0.0.0:80, backlog 511 failed, ignored (95: Operation not supported)
2000/01/01 00:00:03 [emerg] 1000#1000: io_setup() failed (38: Function not implemented)
2000/01/01 00:00:03 [alert] 1000#1000: epoll_wait() timed out (110: Connection timed out)
```

**Reply by stevenengler** [reply]
The important line is the `[emerg] 1000#1000: io_setup() failed (38: Function not implemented)` message. Shadow doesn't support this syscall, but I don't get this message when I run nginx, so it would be helpful if you could post a self-contained simulation (all of the configuration files and website).

One thing you can try is adding the line [`aio off;`](http://nginx.org/en/docs/http/ngx_http_core_module.html#aio) in your nginx config file. If that doesn't help, you can also try adding [`use poll;`](http://nginx.org/en/docs/ngx_core_module.html#use) instead.

**Reply by beenhuang** [reply]
My shadow configuration file is as follows:

```
general:

  stop_time: 10s

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/sbin/nginx
      args: -c /home/shadow/test1/nginx.conf -p .
      start_time: 3s
  client:
    network_node_id: 0
    processes:
    - path: /bin/curl
      args: -s server
      start_time: 5s
```

and I have the file nginx.conf in the same directory:
```
error_log stderr;

# shadow wants to run nginx in the foreground
daemon off;

# shadow doesn't support fork()
master_process off;
worker_processes 0;

# don't use the system pid file
pid /home/shadow/test1/nginx.pid;

events {
  # we're not using any workers, so this is the maximum number
  # of simultaneous connections we can support
  worker_connections 1024;
}

http {
  include             /etc/nginx/mime.types;
  default_type        application/octet-stream;

  # shadow does not support sendfile() nor TCP_NODELAY
  sendfile off;
  tcp_nodelay off;
  
  access_log stdout;
  
  types_hash_max_size 4096;
  
  server {
    listen 80;

    location / {
      root /home/shadow/test3/;
      index index.html;
    }
  }
}
```

I tried the two recommended configurations and the results are as follows：
1. I tried to aid off; , and the above error message is still displayed.
2. the use poll; configuration causes another error.
`nginx: [emerg] invalid event type "poll" in /home/shadow/test1/nginx.conf:17`
