### DISCUSSION TITLE
I want to set up the hidden server using Nginx in the shadow environment. Something goes wrong. How should I do?

### DISCUSSION THREAD

**Discussion by beenhuang** [shadow/shadow#1767] [General]
(Migrated from #1765)

I want to set up the hidden server using Nginx in the shadow environment and implement the following functions:

1. The HS establishes the HS-IP(Introduction Point) circuit and obtains the connection request from the users.
2. After receiving the connection request, the HS establish a circuit with the RP（Rendezvous Point） node to send web page data.
3. The user establishes an client-IP circuit and sends connection requests to the IP node.
4. The user receives a response from the hidden server on the RP Circuit, sends an HTTP request, and receives the web page data from server.

How should I do?

---

Here is the configuration file for nginx, as follows：

```
error_log stderr;

daemon off;

master_process off;
worker_processes 0;

pid /home/shadow/tornet0.01/nginx.conf/nginx.pid;

events {
  worker_connections 1024;
  use poll;
}

http {
  include             /usr/local/nginx/conf/mime.types;
  default_type        application/octet-stream;

  sendfile off;
  tcp_nodelay off;
  aio off;
  
  access_log stdout;
  
  types_hash_max_size 4096;
  
  server {
    listen 8000;
    
    location / {
      root /home/shadow/websites/0/www.baidu.com/;
      index index.html;
    }
  }
}
```

and The torrc configuration for HS  in the conf/tor.hiddenserver.torrc  is as follows:

```
HiddenServiceDir hs
HiddenServicePort 80 127.0.0.1:8000
```

and shadow.data.template/hosts/hiddenserver/hs/hostname :

```
r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion
```

and shadow.config.yaml : 

```
   ...
  relay67middle:
    network_node_id: 635
    ip_addr: 46.163.76.170
    bandwidth_down: 2504 kilobit
    bandwidth_up: 2504 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay67middle --Nickname relay67middle --defaults-torrc torrc-defaults
        -f torrc
      start_time: 5
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 6 
  hiddenserver:
    network_node_id: 206
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: /usr/local/nginx/sbin/nginx
      args: -c /home/shadow/tornet0.01-hs/nginx.conf/nginx.conf -p .
      start_time: 30
    - path: ~/.local/bin/tor
      args: --Address hiddenserver --Nickname hiddenserver
            --defaults-torrc torrc-defaults -f torrc
      start_time: 30
  torhiddenclient1:
    network_node_id: 2090
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address torhiddenclient1 --Nickname torhiddenclient1 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 40
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 41
    - path: /bin/curl
      args: --socks5 127.0.0.1:9050 hiddenserver:8000
      start_time: 60
```

then, The results are as follows:

```
Jan 01 00:08:48.244 [info] log_heartbeat(): Average packaged cell fullness: 97.933%. TLS write overhead: 1%
**Jan 01 00:08:48.244 [notice] Heartbeat: Our onion service received 0 v3 INTRODUCE2 cells and attempted to launch 0 rendezvous circuits.**
Jan 01 00:08:48.244 [debug] circuit_remove_handled_ports(): Port 443 is already being handled; removing.
Jan 01 00:08:48.351 [debug] conn_read_callback(): socket 24 wants to read.
Jan 01 00:08:48.351 [debug] connection_buf_read_from_socket(): 24: starting, inbuf_datalen 0 (0 pending in tls object). at_most 16448.
```

HS did not receive any requests from the client, How should I do?

**Comment by stevenengler** [comment]
> ```
> torhiddenclient1:
>     network_node_id: 2090
>     bandwidth_up: 1000000 kilobit
>     bandwidth_down: 1000000 kilobit
>     processes:
>     - path: ~/.local/bin/tor
>       args: --Address torhiddenclient1 --Nickname torhiddenclient1 --defaults-torrc torrc-defaults
>         -f torrc
>       start_time: 40
>     - path: ~/.local/bin/oniontrace
>       args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
>       start_time: 41
>     - path: /bin/curl
>       args: --socks5 127.0.0.1:9050 hiddenserver:8000
>       start_time: 60
> ```

Your `curl` client needs to connect to the hidden service by it's onion name (`r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion`), not its machine hostname (`hiddenserver`). You should also be connecting on port 80, not 8000.

**Reply by beenhuang** [reply]
I have modified the arguments like this:
> args: --socks5 127.0.0.1:9050 r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion:80

and, the HS still did not receive the request from the client. How should I do?

The following is the torhiddenclient1's torhiddenclient1.curl.1002.shimlog file content, may be useful:

> 00:01:34.923958 [00:01:00.000000004] [shd-shim] [warning] [shim_api_addrinfo.c:410] [shim_api_getaddrinfo] shadow_hostname_to_addr_ipv4 syscall failed for name r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion, falling back to less efficient scan of '/etc/hosts' file.

**Reply by stevenengler** [reply]
You should also use `--socks5-hostname` instead of `--socks5`.

**Reply by beenhuang** [reply]
I have modified the arguments like this:

> args: --socks5-hostname 127.0.0.1:9050 http://r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion:80

The following is the torhiddenclient1.curl.1002.stderr file content:

> curl: (97) Can't complete SOCKS5 connection to r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion

**Reply by stevenengler** [reply]
The error `97` represents "proxy handshake error", which is different from the usual `7` "Couldn't connect to server". So I'm not sure what's going wrong here. You should also try removing the oniontrace process from your client.

**Reply by beenhuang** [reply]
I try removing the oniontrace process, and the same error occurs again. 

I want to a client in the shadow access a hidden server using nginx in the shadow and implement the following functions:
1. The HS establishes the HS-IP(Introduction Point) circuit and obtains the connection request from the users.
2. After receiving the connection request, the HS establish a circuit with the RP（Rendezvous Point） node to send web page data.
3. The user establishes an client-IP circuit and sends connection requests to the IP node.
4. The user receives a response from the hidden server on the RP Circuit, sends an HTTP request, and receives the web page data from server.

Could you provide the correct configuration files? 
Thank you.

**Reply by stevenengler** [reply]
So in summary you just want a simulation where a client (for example curl) downloads a webpage from an nginx hidden service? While nginx does seem to work okay, we don't officially support it so there may be bugs. It may be easier to try to modify the minimal tor test in `shadow/src/test/tor/minimal` to replace the tgen client/server with a curl client and nginx server.

**Reply by beenhuang** [reply]
Well, I have read Rob's "Inside Job: Applying Trafﬁc Analysis to Measure Tor from Within". In the paper, Rob used shadow simulator to collect circuit traffic of a specific hidden server. So I wanted to try and do what he did.I try, and I hope to give more advice, thanks.

**Reply by beenhuang** [reply]
I set up the hidden server using Nginx in shadow. Nginx as a hidden server is not responding to user requests. How should I do?

Here is the configuration file for nginx, as follows：
```
error_log stderr;

daemon off;

master_process off;
worker_processes 0;

pid /home/shadow/tornet0.01-hs2/nginx.conf/nginx.pid;

events {
  worker_connections 1024;
  use poll;
}

http {
  include             /usr/local/nginx/conf/mime.types;
  default_type        application/octet-stream;

  sendfile off;
  tcp_nodelay off;
  aio off;
  
  access_log stdout;
  types_hash_max_size 4096;
  
  server_tokens off;

  server {
    listen 127.0.0.1:8001;
    
    location / {
      root /home/shadow/website/accessible/0/www.google.com/;
      index index.html;
    }
  }
}
```

and The torrc configuration for HS in the conf/tor.hiddenserver.torrc is as follows:

```
HiddenServiceDir hs
HiddenServicePort 8090 127.0.0.1:8001
```

and shadow.config.yaml :

```
  hiddenserver:
    network_node_id: 206
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: /usr/local/nginx/sbin/nginx
      args: -c /home/shadow/tornet0.01-hs2/nginx.conf/nginx.conf -p .
      start_time: 20
    - path: ~/.local/bin/tor
      args: --Address hiddenserver --Nickname hiddenserver
            --defaults-torrc torrc-defaults -f torrc
      start_time: 40
  client1:
    network_node_id: 2090
    bandwidth_up: 1000000 kilobit
    bandwidth_down: 1000000 kilobit
    processes:
    - path: ~/.local/bin/tor
      args: --Address client1 --Nickname client1 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 40
    - path: ~/.local/bin/oniontrace
      args: Mode=log TorControlPort=9051 LogLevel=info Events=BW,CIRC
      start_time: 40
    - path: /bin/curl
      args: --socks5-hostname localhost:9050 r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd.onion:8090
      start_time: 400
```

and client1.tor.1000.stdout:

```
Jan 01 00:06:42.190 [debug] circuit_receive_relay_cell(): Sending to origin.
Jan 01 00:06:42.190 [debug] connection_edge_process_relay_cell(): Now seen 176 relay cells here (command 37, stream 0).
**Jan 01 00:06:42.190 [info] hs_client_receive_rendezvous2(): Got RENDEZVOUS2 cell from hidden service on circuit 2271796149.**
Jan 01 00:06:42.190 [debug] circuit_change_purpose(): changing purpose of origin circ 21 from "Hidden service client: Pending rendezvous point (ack received)" (11) to "Hidden service client: Active rendezvous point" (12)
Jan 01 00:06:42.190 [info] connection_ap_handshake_attach_circuit(): rend joined circ 2271796149 (id: 21) already here. Attaching. (stream 2 sec old)
Jan 01 00:06:42.190 [debug] link_apconn_to_circ(): attaching new conn to circ. n_circ_id 2271796149.
```

and hiddenserver.tor.1001.stdout:

```
Jan 01 00:06:41.581 [debug] connection_edge_process_relay_cell(): Now seen 2604 relay cells here (command 35, stream 0).
Jan 01 00:06:41.581 [info] hs_cell_parse_introduce2(): Received a decodable INTRODUCE2 cell on circuit 3491714312 for service r4aj4kaqf46mala2yykldkvwrrwjagab2qppuqtvgdxwh6spsulwu2qd. Decoding encrypted section...
**Jan 01 00:06:41.581 [info] hs_cell_parse_introduce2(): Valid INTRODUCE2 cell. Launching rendezvous circuit.**
Jan 01 00:06:41.581 [debug] circuit_find_to_cannibalize(): Hunting for a circ to cannibalize: purpose 18, uptime 0, capacity 1, internal 1
Jan 01 00:06:41.581 [info] circuit_launch_by_extend_info(): Cannibalizing circ 4080496121 (id: 498) for purpose 18 (Hidden service: Connecting to rendezvous point)
```

The Rendezvous Circuit has been established between Client and HS. But the user did not received any response from Nginx. How should I do?
