### DISCUSSION TITLE
Configurable port when binding on :0

### DISCUSSION THREAD

**Discussion by trinity-1686a** [shadow/shadow#2596] [Ideas]
Right now when `bind()`ing on port 0, shadow returns a (seeded) random port. In some case it would be helpful to be able to override that with some known port.
Pluggable Transports bind a random port and report which port the bound on their stdout. In a real environment, that would allow their parent (tor, or other software supporting PTs) to know where to connect. As Shadow does not support fork/exec yet, this behavior can't be reproduced, and instead people modify the PT so it bind a fixed port, and tell tor the PT is already started at this address. An example of that can be found [for snowflake](https://gitlab.torproject.org/cohosh/snowflake/-/commit/b6044dd3b49eb1047d86b7c9752bdc11758c401e).

It would be handy if Shadow could have a per-process config which makes bind() on port 0 bind a predefined port (or the next free port if that port is already bound...)

it could look something like
```yaml
processes:
- path: ~/.local/bin/snowflake-client
  environment: 'TOR_PT_MANAGED_TRANSPORT_VER=1;TOR_PT_CLIENT_TRANSPORTS=snowflake'
  args: -ice "stun:stun:3478" -url "http://broker:8080" -keep-local-addresses -log "pt.log" -unsafe-logging
  start_time: 90
  bind_port_start: 9000
```
