### DISCUSSION TITLE
Basic examples failing - how to go about debuging for a newbie to shadow

### DISCUSSION THREAD

**Discussion by idjordje** [shadow/shadow#3508] [Q&A]
I cloned latest and tried to run basic examples to learn about the capabilities but basic file transfer test fails with message:

```
shadow shadow.yaml > shadow.log
** Starting Shadow 3.2.0
Error: process 'server.python3.13.1000' exited with status Normal(1); expected end state was running but was exited: 1
Error: process 'client2.curl.1000' exited with status StoppedByShadow; expected end state was exited: 0 but was running
Error: process 'client3.curl.1000' exited with status StoppedByShadow; expected end state was exited: 0 but was running
Error: process 'client1.curl.1000' exited with status StoppedByShadow; expected end state was exited: 0 but was running
Error: Failed to run the simulation
Error:
Error: Caused by:
Error:     4 managed processes in unexpected final state
** Shadow did not complete successfully: Failed to run the simulation
**   4 managed processes in unexpected final state
** See the log for details
```

output of `uname -a`

```
Linux ivand-MBAir6-1 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Sat Jan 11 00:06:25 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

The work area is cloned yesterday (02/06/2025) and build passes cleanly and test passed with all but two regressions:

```
The following tests FAILED:
        102 - regression-2210-shadow (Failed)
        103 - regression-3148-shadow (Failed)
        149 - ioctl-linux (Failed)
Errors while running CTest
Output from these tests are in: /home/ivand/proj/shadow/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
2025-02-07 17:37:14,149 [INFO] ctest returned 8
```

BTW ... `--output-on-failure` is not recognized as valid option

-Ivan

**Comment by stevenengler** [comment]
Thanks for the bug report!

So everything seems to work fine for me in an Ubuntu 24.04 container with Linux 6.11.10. Are you running in a container, or directly on the host?

What's interesting is that all of the simulations that fail for you are using Python: the web server in the "basic file transfer" test, and inline python scripts in the two regression tests. The ioctl test is only failing under Linux and not Shadow, which is okay.

Can you post the output of `python3 -V`?

Can you try running the following simulation, and post the log output (`shadow.log`) here if it fails?

```yaml
general:
  stop_time: 10 seconds
network:
  graph:
    type: 1_gbit_switch
hosts:
  testnode:
    network_node_id: 0
    processes:
    - path: python3
      args: '-c "print(\"hello world\")"'
      start_time: 3
      expected_final_state: { exited: 0 }
```

```bash
shadow --log-level=trace shadow.yaml > shadow.log
```

If there are too many log lines, you can use a log level of `debug` instead.

**Reply by stevenengler** [reply]
Also, if it fails can you try this simulation?

```yaml
general:
  stop_time: 10 seconds
network:
  graph:
    type: 1_gbit_switch
hosts:
  testnode:
    network_node_id: 0
    processes:
    - path: bash
      args: '-c "echo \"hello world\""'
      start_time: 3
      expected_final_state: { exited: 0 }
```
