### ISSUE TITLE
Remove the plugins list from the root of the configuration file

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1147]
The current configuration file format requires you to list plugins and their paths in the configuration root, and then refer to those plugins when specifying processes. For example:

```yaml
plugins:
- id: myplugin
  path: tor/src/app/tor
hosts:
- id: mynode
  quantity: 1
  processes:
  - plugin: myplugin
    starttime: 1
```

It would be simpler to remove the plugins list at the root of the configuration file and require proceses to specify the path directly. For example:

```yaml
hosts:
- id: mynode
  quantity: 1
  processes:
  - plugin: tor/src/app/tor
    starttime: 1
```
