### ISSUE TITLE
g_hash_table_remove_internal: assertion 'hash_table != NULL' failed

### ISSUE THREAD

**Issue by marcosimioni** [shadow/shadow#1537]
**Describe the issue**
I'm getting in console the following error:

```
(process:30852): GLib-CRITICAL **: 16:26:58.368: g_hash_table_remove_internal: assertion 'hash_table != NULL' failed
```

How can I investigate what's causing the error?
What should I look for in the shadow.log file?

Couldn't find anything interesting yet, that error message simply pops up in console.

**To Reproduce**
I'm not sure yet. I have a simulation where I'm using start/stop times on a few nodes.
I'm reporting below in the "Additional context" section an excerpt of shadow.config file.

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
 ```Description:    Ubuntu 18.04.5 LTS```

 - Kernel version: post the output of `uname -a`  
 ```Linux <redacted> 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
```Shadow 2.0.0-pre.4```, commit ```103814bfff08b7ddfb1960bc9e263dbaeb437ecc```

 - Which plug-ins you are using:  
```Tor version 0.4.5.8 (git-27e5e33d2ca35de8).```

**Additional context**
Below an excerpt of shadow.config file where I'm using start and stop times.
Please note I am doing this on a number of hidden service nodes.

It looks convoluted, but in short:
- tor starts, after 60 seconds tgen starts...
- ... after a while ...
- tgen stops, after 60 seconds tor stops, rm lock...
- ... after a while ...
- tor2 starts, tgen2 starts.

```
  hiddenservice11:
    options:
      country_code_hint: DE
      pcap_directory: pcap
    bandwidth_up: 100000000 kilobit
    bandwidth_down: 100000000 kilobit
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 300
      stop_time: 1740
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen-server.tgenrc.graphml
      start_time: 2460
    - path: ~/.local/bin/tor
      args: --Address hiddenservice11 --Nickname hiddenservice11 --defaults-torrc
        torrc-defaults -f torrc
      start_time: 240
      stop_time: 1800
    - path: /bin/rm
      args: lock
      start_time: 1810
    - path: ~/.local/bin/tor
      args: --Address hiddenservice11 --Nickname hiddenservice11 --defaults-torrc
        torrc-defaults -f torrc
      start_time: 2400
```
