### ISSUE TITLE
Incorrect packets retransmissions after process is killed and sockets have been closed? 

### ISSUE THREAD

**Issue by marcosimioni** [shadow/shadow#1550]
**Describe the issue**
When a process is stopped and all its sockets are then shut down, shadow keeps retransmitting its packets.

**To Reproduce**
Modify the Tor minimal configuration as follows (note that I have enabled PCAP recording, and also that I am stopping the hiddenservice's Tor process at t=1505, which is right after the torhiddenclient's TGen starts kicking in at 1500):

```
general:
  stop_time: 30 min
network:
  graph:
    type: gml
    inline: |
      graph [
        directed 0
        node [
          id 0
          ip_address "0.0.0.0"
          country_code "US"
          bandwidth_down "1 Gbit"
          bandwidth_up "1 Gbit"
        ]
        edge [
          source 0
          target 0
          latency "50 ms"
          jitter "0 ms"
          packet_loss 0.0
        ]
      ]
hosts:
  fileserver:
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.server.graphml.xml
      start_time: 1
  hiddenserver:
    options:
      pcap_directory: pcap
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.hiddenserver.graphml.xml
      start_time: 1
    - path: ~/.local/bin/tor
      args: --Address hiddenserver --Nickname hiddenserver
            --defaults-torrc torrc-defaults -f torrc
      start_time: 900
      stop_time: 1505
  4uthority:
    options:
      ip_address_hint: 100.0.0.1
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority --Nickname 4uthority
            --defaults-torrc torrc-defaults -f torrc
      start_time: 1
  exit1:
    processes:
    - path: ~/.local/bin/tor
      args: --Address exit1 --Nickname exit1
            --defaults-torrc torrc-defaults -f torrc
      start_time: 60
  exit2:
    processes:
    - path: ~/.local/bin/tor
      args: --Address exit2 --Nickname exit2
            --defaults-torrc torrc-defaults -f torrc
      start_time: 60
  relay1:
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay1 --Nickname relay1
            --defaults-torrc torrc-defaults -f torrc
      start_time: 60
  relay2:
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay2 --Nickname relay2
            --defaults-torrc torrc-defaults -f torrc
      start_time: 60
  client:
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.client.graphml.xml
      start_time: 600
  torclient:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient --Nickname torclient
            --defaults-torrc torrc-defaults -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient.graphml.xml
      start_time: 1500
  torbridgeclient:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torbridgeclient --Nickname torbridgeclient
            --UseBridges 1 --Bridge 100.0.0.1:9111
            --defaults-torrc torrc-defaults -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient.graphml.xml
      start_time: 1500
  torhiddenclient:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torhiddenclient --Nickname torhiddenclient
            --defaults-torrc torrc-defaults -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torhiddenclient.graphml.xml
      start_time: 1500
```

Run the simulation with `./run.sh`, and confirm via `tail shadow.data/hosts/hiddenserver/hiddenserver.tor.1001.stdout` that the tor process was stopped at approx t=`Jan 01 00:25:05` and there are not log entries after that mark.

Now observe the generated `hiddenserver-11.0.0.5.pcap` file at around t=1505 mark (if you're using Wireshark make sure you're looking at timestamps since 1970-01-01, via menu View->Time Display Format, and not since the beginning of capture), containing retransmitted packets generated by 11.0.0.5:

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/22682005/127770289-799689ba-1d7b-4948-8d40-0eaa48579edc.png">

And they continue...

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/22682005/127770613-4706ccf5-8929-49c7-8f1f-20bdd98ae82c.png">

Observe there are a lot of retransmissions with src ip = 11.0.0.5, which is the hiddenservice host's IP.

I would expect that after t=1505 the Tor process is killed, therefore all its sockets are closed and there should be no retransmissions, or am I missing something or misinterpreting Wireshark?

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
 `Description:    Ubuntu 18.04.5 LTS`

 - Kernel version: post the output of `uname -a`  
`Linux ***** 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
`Shadow 2.0.0-pre.4`

 - Which plug-ins you are using:  
`Tor`

**Additional context**
