### ISSUE TITLE
Timestamps in pcap files are wrong

### ISSUE THREAD

**Issue by lorenzo9uerra** [shadow/shadow#1585]
**Describe the issue**
Using the pcap saving functionality built in shadow, I noticed the timestamps sometimes are wrong and they even go back in time. For example the SYN ACK of the server comes before than the SYN of the client and most of the packets have "Out-of-order" errors.

_Edit: I updated to the last commit which is d64d07c65859090dc76a27fb3d9ef44ea9d756f3 and timestamps got even worse, they rarely have decimal values and when they do it's because the ones from the server are saved ~0.01s earlier than from the client, which in itself is not possible, and now that timestamps got even more rounded they are almost useless for my case.
The issue I opened was relative to commit 9192077bf0042fedd89d925c03a351c3ff0ecd8d, when the main problem was out of sync packets and timestamps that didn't include the latency specified in the network graph config. It got worse since then._

**To Reproduce**
this is the configuration I used for the simulation:
```yaml
general:
  stop_time: 30 min
  seed: 1835250621
network:
  graph:
    type: gml
    inline: |
      graph [
        directed 0
        node [
          id 0
          ip_address "0.0.0.0"
          country_code "US"
          bandwidth_down "1 Gbit"
          bandwidth_up "1 Gbit"
        ]
        edge [
          source 0
          target 0
          latency "150 ms"
          jitter "0 ms"
          packet_loss 0.0
        ]
      ]
host_defaults:
  pcap_directory: ./pcaps
hosts:
  fileserver0:
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.server.graphml.xml
      start_time: 1
  fileserver1:
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.server.graphml.xml
      start_time: 1
  fileserver2:
    processes:
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.server.graphml.xml
      start_time: 1
  4uthority:
    options:
      ip_address_hint: 100.0.0.1
    processes:
    - path: ~/.local/bin/tor
      args: --Address 4uthority --Nickname 4uthority --defaults-torrc torrc-defaults
        -f torrc
      start_time: 1
  exit1:
    processes:
    - path: ~/.local/bin/tor
      args: --Address exit1 --Nickname exit1 --defaults-torrc torrc-defaults -f torrc
      start_time: 60
  exit2:
    processes:
    - path: ~/.local/bin/tor
      args: --Address exit2 --Nickname exit2 --defaults-torrc torrc-defaults -f torrc
      start_time: 60
  relay1:
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay1 --Nickname relay1 --defaults-torrc torrc-defaults -f
        torrc
      start_time: 60
  relay2:
    processes:
    - path: ~/.local/bin/tor
      args: --Address relay2 --Nickname relay2 --defaults-torrc torrc-defaults -f
        torrc
      start_time: 60
  torclient0:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient0 --Nickname torclient0 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient0.graphml.xml
      start_time: 1200
  torclient1:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient1 --Nickname torclient1 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient1.graphml.xml
      start_time: 1200
  torclient2:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient2 --Nickname torclient2 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient2.graphml.xml
      start_time: 1200
  torclient3:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient3 --Nickname torclient3 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient3.graphml.xml
      start_time: 1200
  torclient4:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient4 --Nickname torclient4 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient4.graphml.xml
      start_time: 1200
  torclient5:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient5 --Nickname torclient5 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient5.graphml.xml
      start_time: 1200
  torclient6:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient6 --Nickname torclient6 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient6.graphml.xml
      start_time: 1200
  torclient7:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient7 --Nickname torclient7 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient7.graphml.xml
      start_time: 1200
  torclient8:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient8 --Nickname torclient8 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient8.graphml.xml
      start_time: 1200
  torclient9:
    processes:
    - path: ~/.local/bin/tor
      args: --Address torclient9 --Nickname torclient9 --defaults-torrc torrc-defaults
        -f torrc
      start_time: 900
    - path: ~/.local/bin/tgen
      args: ../../../conf/tgen.torclient9.graphml.xml
      start_time: 1200
```
Every other configuration is the same as the tor minimal test inside src/test/tor, except for the torclient tgen configurations, which have all the same configuartion except for randomly-chosen fileservers:
```xml
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="socksproxy" attr.type="string" for="node" id="d7" />
  <key attr.name="peers" attr.type="string" for="node" id="d5" />
  <key attr.name="sendsize" attr.type="string" for="node" id="d3" />
  <key attr.name="recvsize" attr.type="string" for="node" id="d2" />
  <key attr.name="count" attr.type="string" for="node" id="d1" />
  <key attr.name="time" attr.type="string" for="node" id="d0" />
  <graph edgedefault="directed">
    <node id="start">
      <data key="d5">fileserver0:80</data>
      <data key="d7">localhost:9000</data>
    </node>
    <node id="stream">
      <data key="d2">1 MiB</data>
      <data key="d3">1 KiB</data>
    </node>
    <node id="pause">
      <data key="d0">100 ms,200 ms,300 ms,400 ms,500 ms,600 ms,700 ms,800 ms,900 ms,1,2,3,4,5,6,7,8,9,10</data>
    </node>
    <node id="end">
      <data key="d1">10</data>
      <data key="d0">8 minutes</data>
    </node>
    <edge source="start" target="stream" />
    <edge source="stream" target="end" />
    <edge source="end" target="pause" />
    <edge source="pause" target="start" />
  </graph>
</graphml>
```
Here are the packets out of sync:
```yaml
----
# Packet 5006 from fileserver2-11.0.0.5.pcap
- 5007
- 34.811000
- 11.0.0.5
- 11.0.0.1
- TCP
- 66
- 80 → 49812 [SYN, ACK] Seq=0 Ack=1 Win=121 Len=0
```
```yaml
----
# Packet 3898 from torclient5-127.0.0.1.pcap
- 3899
- 34.821000
- 127.0.0.1
- 127.0.0.1
- TCP
- 66
- 38036 → 9000 [SYN] Seq=0 Win=121 Len=0
```
And yes, I checked they weren't related to other streams, but it was the beginning of the same stream.

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
Arch Linux
 - Kernel version: post the output of `uname -a`  
Linux hostname 5.13.12-arch1-1 # 1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v2.0.0-pre.4-50-gc5968af2-dirty 2021-08-06--11:25:10 with GLib v2.68.3 and IGraph v0.8.0
 - Which plug-ins you are using:  
none

**Additional context**
I'm not using a virtual machine

**Comment by stevenengler** [comment]
> Describe the issue
Using the pcap saving functionality built in shadow, I noticed the timestamps sometimes are wrong and they even go back in time. For example the SYN ACK of the server comes before than the SYN of the client and most of the packets have "Out-of-order" errors.

Can you show an example or screenshot of the timestamps going back in time? I can't reproduce that. There was a bug where two packets could be recorded out of order (this will be fixed with #1595), but the timestamps are the same and I don't see them going back in time.

> Edit: I updated to the last commit which is d64d07c and timestamps got even worse, they rarely have decimal values and when they do it's because the ones from the server are saved ~0.01s earlier than from the client, which in itself is not possible, and now that timestamps got even more rounded they are almost useless for my case.

Which timestamps are you using? When using wireshark, the frame epoch time shows fractional seconds for me.

> The issue I opened was relative to commit 9192077, when the main problem was out of sync packets and timestamps that didn't include the latency specified in the network graph config. It got worse since then.

I'm also not able to reproduce the missing latency. Can you try with the following network? And if you see the same issues with this network, can you attach the generated pcap files? (Make sure that #1595 is merged first before testing.)

```yaml
general:
  stop_time: 10
network:
  graph:
    type: gml
    inline: |
      graph [
        node [
          id 0
          host_bandwidth_down "100 Mbit"
          host_bandwidth_up "100 Mbit"
        ]
        edge [
          source 0
          target 0
          latency "500 ms"
        ]
      ]
host_defaults:
  pcap_directory: 'pcaps'
hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/bin/python3
      args: -m http.server 80
      start_time: 3
  client:
    network_node_id: 0
    quantity: 3
    processes:
    - path: /usr/bin/curl
      args: -s server
      start_time: 5
```
