### ISSUE TITLE
Repeated FIN packets without acknowledgement

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1596]
**Describe the issue**

TCP endpoints don't seem to ACK the FIN packet. In the following screenshot showing a small HTTP request from a client (11.0.0.1) to a server (11.0.0.4), the client sends the GET request, the server sends the response, the client sends a FIN, and then the server sends a FIN. But neither the server nor client acknowledge the FIN, so they continue sending FIN messages to each other once every second.

![1629780829_grim](https://user-images.githubusercontent.com/3708797/130557924-cc16b949-59b7-4689-abc5-007bcba93148.png)

**To Reproduce**

```yaml
general:
  stop_time: 20
network:
  graph:
    type: gml
    inline: |
      graph [
        node [
          id 0
          host_bandwidth_down "140 Mbit"
          host_bandwidth_up "18 Mbit"
        ]
        edge [
          source 0
          target 0
          latency "100 ms"
          packet_loss 0.01
        ]
      ]
host_defaults:
  pcap_directory: 'pcaps'
hosts:
  server:
    network_node_id: 0
    quantity: 1
    processes:
    - path: /usr/bin/python3
      args: -m http.server 80
      start_time: 3
  client:
    network_node_id: 0
    quantity: 3
    processes:
    - path: /usr/bin/curl
      args: -s server
      start_time: 5
```

Using the shadow version from #1595.
