### ISSUE TITLE
Shadow did not complete successfully: Could not parse configuration file "shadow.yaml"

### ISSUE THREAD

**Issue by gswanx** [shadow/shadow#1657]
I  am installing and using shadow for the first time . I  followed the readme file to install all the dependency and installed Shadow  successfully. But when I followed [this page](https://github.com/shadow/shadow/blob/main/docs/getting_started_basic.md) of the documentation to run the first basic example, I encountered this error:
When running`shadow shadow.yaml > shadow.log` 
I got the following message:
```
** Shadow did not complete successfully: Could not parse configuration file "shadow.yaml"
** See the log for details
```

**Operating System :**
Ubuntu 20.04 LTS on VMware Workstation 15.5pro
**Kernel version:** 
Linux tor-ubuntu 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Shadow:**
Shadow v2.0.0-pre.4-215-ge4c319dd 2021-09-20--18:12:16

**Comment by stevenengler** [comment]
Thanks for the report, I added #1658 and #1659 which should fix these issues. The example should have included the config line `network_node_id: 0` for each process. Try the following config instead (and make sure `/bin/python3` and `/bin/curl` are valid binaries on your system):

```yaml
general:
  # stop after 10 simulated seconds
  stop_time: 10s

network:
  graph:
    # use a built-in network graph containing
    # a single vertex with a bandwidth of 1 Gbit
    type: 1_gbit_switch

hosts:
  # a host with the hostname 'server'
  server:
    network_node_id: 0
    processes:
    - path: /bin/python3
      args: -m http.server 80
      start_time: 3s
  # three hosts with hostnames 'client1', 'client2', and 'client3'
  client:
    quantity: 3
    network_node_id: 0
    processes:
    - path: /bin/curl
      args: -s server
      start_time: 5s
```
