### ISSUE TITLE
Users in shadow could not access local nginx server in shadow

### ISSUE THREAD

**Issue by beenhuang** [shadow/shadow#1739]
I modified the shadow.yaml in the getting_started_basic.md file, as below:

```yaml
general:
  stop_time: 10s

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/local/nginx/sbin/nginx
      start_time: 3s

  client:
    quantity: 3
    network_node_id: 0
    processes:
    - path: /bin/curl
      args: -s server
      start_time: 5s
```

Then, Users in shadow could not access the local nginx server in shadow, and I have confirmed that the Nginx is working properly. (Enter `curl -s 127.0.0.1` in the command window and could get the web page information). How should I modify the configuration file？
