### ISSUE TITLE
Remove configuration `hosts.<hostname>.quantity` field

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2067]
Shadow supports a [`hosts.<hostname>.quantity`](https://shadow.github.io/docs/guide/shadow_config_spec.html#hostshostnamequantity) field to make it easier to start multiple hosts that run the same processes. For example, we use it in our curl example to start three clients:

```yaml
hosts:
  # a host with the hostname 'server'
  server:
    network_node_id: 0
    processes:
    - path: /usr/bin/python3
      args: -m http.server 80
      start_time: 3s
  # three hosts with hostnames 'client1', 'client2', and 'client3'
  client:
    network_node_id: 0
    quantity: 3
    processes:
    - path: /usr/bin/curl
      args: -s server
      start_time: 5s
```

I think we should consider removing this option, and instead recommend using yaml anchors instead. The previous example can be replaced by:

```yaml
hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/bin/python3
      args: -m http.server 80
      start_time: 3s
  client1: &client_host
    network_node_id: 0
    processes:
    - path: /usr/bin/curl
      args: -s server
      start_time: 5s
  client2: *client_host
  client3: *client_host
```

There is also a `hosts.<hostname>.processes[*].quantity` field we may also want to consider removing.

This syntax is already supported in shadow today.
