### ISSUE TITLE
JACK daemon fails to start (missing support for shared memory, realtime priorities, semaphore function)

### ISSUE THREAD

**Issue by ntonnaett** [shadow/shadow#2392]
**Describe the issue**
I want to run [JackTrip](https://github.com/jacktrip/jacktrip) in Shadow. JackTrip is an Audio over IP software that uses the JACK sound server as audio backend. JACK uses shared memory and usually wants to set its realtime priority. Both doesn't seem to work in Shadow. It looks like a semaphore function is missing too.

What needs to be done getting this to work?

server.jackd.1000.stderr:
```
sched_get_priority_min() failed.
Cannot set scheduling priority for messagebuffer thread: Invalid argument (22)
Cannot set scheduling priority for messagebuffer thread: Invalid argument (22)
Cannot set scheduling priority for messagebuffer thread: Invalid argument (22)
JACK semaphore error: semget creation (Function not implemented)
jack_shm_lock_registry fails...
No access to shm registry
Failed to open server
```

**To Reproduce**
Install JACK and JackTrip (on Fedora 36):
```bash
sudo dnf swap pipewire-jack-audio-connection-kit jack-audio-connection-kit
sudo dnf install jacktrip
```

shadow.yml:
```yaml
general:
  stop_time: 30s
  model_unblocked_syscall_latency: true

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/bin/jackd
      args: -r -d dummy --rate 48000 --period 128
      start_time: 3s
    - path: /usr/local/bin/jacktrip
      args: -S -z -p4 -q auto -I 1
      start_time: 7s
  client:
    network_node_id: 0
    quantity: 3
    processes:
    - path: /usr/bin/jackd
      args: -r -d dummy --rate 48000 --period 128
      start_time: 5s
    - path: /usr/local/bin/jacktrip
      args: -C server -z -q auto
      start_time: 10s
```

**Operating System (please complete the following information):**
 - OS and version: Fedora release 36 (Thirty Six)
 - Kernel version: Linux newmark 5.18.19-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 21 15:52:59 UTC 2022 x86_64 

**Shadow (please complete the following information):**
 - Version: Shadow v2.2.0-227-g9614fca0 2022-08-29--13:50:24
