### ISSUE TITLE
Simple node.js http server does not run correctly

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2452]
The following http server (adapted from the node.js [getting started guide](https://nodejs.org/en/docs/guides/getting-started-guide/)) does not run correctly in shadow.

```js
const http = require('http');

const hostname = '0.0.0.0';
const port = 80;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

```yaml
general:
  stop_time: 10s
  model_unblocked_syscall_latency: true

network:
  graph:
    type: 1_gbit_switch

hosts:
  server:
    network_node_id: 0
    processes:
    - path: /usr/bin/node
      args: ../../../server.js
      start_time: 3s
  client:
    network_node_id: 0
    processes:
    - path: /usr/bin/curl
      args: server
      start_time: 5s
```

```
apt install npm
rm -rf shadow.data && ../shadow/build/src/main/shadow --strace-logging-mode standard --log-level trace shadow.yaml > shadow.log
```

It fails to write the http response to the socket.

```
curl: (52) Empty reply from server
```

The log shows the following during a `writev`:

```
00:00:04.414467 [29570:shadow-worker] 00:00:05.003366400 [DEBUG] [server:11.0.0.2] [uio.c:69] [_syscallhandler_validateVecParams] Invalid size 0 in iovec[1]
```

This seems to be part of #2379.

There may be other issues in addition to this `writev` bug, but this seems like a good place to start.
