### ISSUE TITLE
Output files are empty for processes that don't exit

### ISSUE THREAD

**Issue by haxxpop** [shadow/shadow#2597]
**Describe the issue**

I noticed that the managed processes that run forever (don't end themselves) will not produce the output files (stdout and stderr files)

I'm not sure if this is the intended behavior, but I think it's a good idea to see the output files of such processes.

**To Reproduce**

You can follow the tutorial to see the issue https://shadow.github.io/docs/guide/getting_started_basic.html

After running `shadow shadow.yaml > shadow.log` as described in the tutorial you will see that the files in `shadow.data/hosts/server/` are empty.

**Operating System (please complete the following information):**
 - OS and version: Ubuntu 20.04.5 LTS
 - Kernel version: Linux thinkpad-t14-g2 5.14.0-1054-oem # 61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Shadow (please complete the following information):**
 - Version: Shadow v2.3.0-0-gb09b00ed-dirty 2022-11-29--13:01:25  
 - Which plug-ins you are using:  "/usr/bin/python3 -m http.server 80"

**Additional context**

**Comment by stevenengler** [comment]
What's happening here is that when the simulation ends, Shadow sends a SIGKILL to all of the processes. Since some applications such as python will buffer their output before writing it to a file, any buffered output won't be written to disk after the SIGKILL.

For python applications, you can add the `-u` flag:

> -u     Force the stdout and stderr streams to be unbuffered.

In the example simulation, it would be `args: -u -m http.server 80`.

For applications in general, you should shut them down properly with a SIGTERM or SIGINT before the simulation ends. For example with a simulation `stop_time` of 10 seconds:

```yaml
processes:
- path: python3
  args: -u -m http.server 80
- path: kill
  args: -s SIGINT 1000
  start_time: 9s
```

Our pid assignment is [documented](https://shadow.github.io/docs/guide/shadow_config_spec.html?highlight=pid#hostshostnameprocesses).

**Comment by stevenengler** [comment]
Before closing this, we should add the `-u` flag to our Python examples, and possibly a `kill <pid>` to other examples.

Related: https://github.com/shadow/shadow/discussions/2034

**Comment by sporksmith** [comment]
Do we want to make it easier to specify "end time - x" before adding `kill` to our examples? Or is that too much scope creep? e.g.

```
processes:
- path: python3
  args: -u -m http.server 80
- path: kill
  args: -s SIGINT 1000
  # 1ms before simulation end
  start_time: -1ms
```
