### ISSUE TITLE
Recent regression in launching java under shadow

### ISSUE THREAD

**Issue by hammer498** [shadow/shadow#2625]
**Describe the issue**
[A previous change](https://github.com/shadow/shadow/issues/2094) allowed java to launch under shadow.  [This commit](https://github.com/shadow/shadow/commit/4ba2a0f8f7ee98feb001e62c3e77252a89310a4e) seems to have caused a regression where loading java now crashes with
> fatal error: pthread_getattr_np failed with error = 3 

Error 3 is `ESRCH` and it looks like that commit added it as an error code in some situations

**To Reproduce**
Same instructions as from the original issue which enabled java support
```
general:
  stop_time: 15s
network:
  graph:
    type: 1_gbit_switch
hosts:
  h1:
    network_node_id: 0
    ip_addr: "11.0.0.1"
    processes:
    - path: /usr/bin/java
      args: --version
```

**Operating System (please complete the following information):**
Running in an ubuntu docker image on mac osx

> lsb_release -d
Description:	Ubuntu 20.04.5 LTS
uname -a
Linux 134296edcd2f 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)

**Shadow (please complete the following information):**

>shadow --version
Shadow v2.3.0-83-g4ba2a0f8 2022-12-12--22:41:52

more specifically though it is broken in every commit after the one referenced above

 - Which plug-ins you are using:  
I don't think I am using any
