### ISSUE TITLE
Host-specific log level appears to be broken

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2643]
If I add the following to the tor minimal test case (with shadow built in debug mode), I do not see trace-level logs for that host in shadow's log:

```yaml
torhiddenclient:
  network_node_id: 0
  options:
    log_level: trace
  processes:
    [...]
```
