### ISSUE TITLE
Picoquic crashes at launch time inside shadow

### ISSUE THREAD

**Issue by FlyearthR** [shadow/shadow#2754]
**Describe the issue**
I am trying to run Picoquic inside shadow, but Picoquic crashes at launch time. Even with `--debug-hosts` in shadow, picoquic terminates before gdb could plug in. There is a `kill: ESRCH`

**To Reproduce**
To reproduce my environment, you can build this Dockerfile:
```
FROM ubuntu:18.04

WORKDIR /

RUN apt-get update && apt-get install libssl-dev git faketime libscope-guard-perl libtest-tcp-perl -y
RUN git clone https://github.com/shadow/shadow.git && cd /shadow && git checkout 264a05bf7aa993e633044d7459052db67c9ba0a4

WORKDIR /shadow

ENV CC gcc
ENV CONTAINER ubuntu:18.04
ENV BUILDTYPE release
ENV RUSTPROFILE minimal

RUN ci/container_scripts/install_deps.sh && ci/container_scripts/install_extra_deps.sh

ENV PATH "/root/.cargo/bin:${PATH}"
RUN ci/container_scripts/build_and_install.sh

ENV PATH="/root/.local/bin:${PATH}"

RUN mkdir -p /tmp/QUIC-FormalVerification/quic-implementations

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

RUN git clone https://github.com/h2o/picotls.git

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/picotls
RUN git checkout 047c5fe20bb9ea91c1caded8977134f19681ec76 && git submodule init && git submodule update && OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake . && make

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations
RUN git clone https://github.com/private-octopus/picoquic.git && cd picoquic && git checkout bb67995f2d7c0e577c2c8788313c3b580d3df9a7
RUN cd picoquic && /usr/bin/cmake . && make

WORKDIR /tmp/QUIC-FormalVerification
```
Then you can run it with `docker run --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=1024g --rm --security-opt seccomp=unconfined -it <container_name>:latest`
Inside the container, you can see that picoquic starts properly with the command `/tmp/QUIC-FormalVerification/quic-implementations/picoquic/picoquicdemo 11.0.0.1 4443`
But if you start it with this `shadow.yaml`
```
general:
  # stop after 10 simulated seconds
  stop_time: 10s
  # old versions of cURL use a busy loop, so to avoid spinning in this busy
  # loop indefinitely, we add a system call latency to advance the simulated
  # time when running non-blocking system calls
  model_unblocked_syscall_latency: true

network:
  graph:
    # use a built-in network graph containing
    # a single vertex with a bandwidth of 1 Gbit
    type: 1_gbit_switch

hosts:
  client:
    network_node_id: 0
    quantity: 1
    ip_addr: "11.0.0.2"
    processes:
    - path: /tmp/QUIC-FormalVerification/quic-implementations/picoquic/picoquicdemo
      args: 11.0.0.1 4443
```
picoquic crashes with return code 139 and without printing anything nor beeing GDBizable (`process XXX is a zombie - the process has already terminated`)
**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
Ubuntu 18.04 in a Docker container
 - Kernel version: post the output of `uname -a`  
`Linux 5fdbaa317768 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v2.4.0-0-g264a05bf 2023-01-25--10:28:35
 - Which plug-ins you are using:  
None
