### ISSUE TITLE
Shadow can take a long time to start processes

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2910]
This has been an issue in Shadow for a while, but it's become much more noticeable when running on our new benchmark runner. In some simulations, Shadow can take a very long time to start processes. This is not deterministic and only happens occasionally.

In the graph below you can see that Shadow seems to get stuck for a while around the simtimes 0:00, 4:00, and 5:00. These simtimes align with when processes are started in the Shadow config (with hundreds of hosts; shortened to only show start times):

```yaml
  4uthority1:
    processes:
    - path: ~/.local/bin/tor
      start_time: 1 # 0:01
    - path: ~/.local/bin/oniontrace
      start_time: 2 # 0:02
  server1exit:
    processes:
    - path: ~/.local/bin/tgen
      start_time: 300 # 5:00
  perfclient1exit:
    processes:
    - path: ~/.local/bin/tor
      start_time: 240 # 4:00
    - path: ~/.local/bin/oniontrace
      start_time: 241 # 4:01
    - path: ~/.local/bin/tgen
      start_time: 300 # 5:00
```

Here we see Shadow taking over an hour (about 33% of the total simulation runtime) to launch processes.

https://github.com/shadow/benchmark-results/tree/master/tor/2023-05-07-T19-52-20

![1683554926_grim](https://user-images.githubusercontent.com/3708797/236846672-ed0b5661-9b93-4db6-97d2-2a0e7b538ea0.png)

I'm not really sure why this might be happening, or what we could do to debug it as it's not reproducible. It could be the fork itself (`clone` in `posix_spawn`) that takes a while, but we use `CLONE_VM` which removes the obvious case of expensive page-table duplication. Maybe there could be some resource exhaustion when starting multiple processes that slows down the simulation. For example does Linux re-seed anything when forking processes (maybe something along the lines of ["Random numbers and virtual-machine forks"](https://lwn.net/Articles/887207/)), which could potentially use and deplete system entropy. Or maybe a library used by the managed processes uses system entropy to initialize something in a `__constructor__` that runs before Shadow can intercept syscalls? Openssl could be a contender for this, but we see the delay even when launching tgen, so this seems unlikely.
