### ISSUE TITLE
Livelock with Ivy

### ISSUE THREAD

**Issue by FlyearthR** [shadow/shadow#2940]
**Describe the issue**
When run within shadow, my quic implementation tester runs endlessly (I stopped it after several days). Out of shadow, it finishes in 10~20 seconds. When inspected with gdb, the process is not blocked on a specific instruction, it runs. The tester is used against picoquic.

**To Reproduce**
To reproduce my environment, you can build this (quite big, built=10Go) Dockerfile:
```
FROM ubuntu:18.04

WORKDIR /tmp
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install python3-pyqt5 python3-pip python-pip libssl-dev git faketime libscope-guard-perl libtest-tcp-perl python2.7 python3 cmake pkg-config iproute2 sudo vim tshark iptables -y
RUN git clone https://github.com/FlyearthR/QUIC-FormalVerification.git && cd QUIC-FormalVerification && git checkout shadow && git submodule update --init --recursive
WORKDIR /tmp/QUIC-FormalVerification/QUIC-Ivy

RUN DEBIAN_FRONTEND="noninteractive" mkdir -p /usr/local/lib/python2.7/dist-packages \ 
 && DEBIAN_FRONTEND="noninteractive" pip install chardet gperf pandas scandir ply plantuml \
 && DEBIAN_FRONTEND="noninteractive" pip3 install progressbar2 pexpect requests scapy \
 && DEBIAN_FRONTEND="noninteractive" python2.7 build_submodules.py \
 && DEBIAN_FRONTEND="noninteractive" pip2 install ms-ivy==1.8.23 #global install


ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /

RUN git clone https://github.com/shadow/shadow.git && cd /shadow && git checkout 264a05bf7aa993e633044d7459052db67c9ba0a4

WORKDIR /shadow

ENV CC gcc
ENV CONTAINER ubuntu:18.04
ENV BUILDTYPE release
ENV RUSTPROFILE minimal

RUN ci/container_scripts/install_deps.sh && ci/container_scripts/install_extra_deps.sh

ENV PATH "/root/.cargo/bin:${PATH}"
RUN ci/container_scripts/build_and_install.sh

ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

RUN git clone https://github.com/h2o/picotls.git

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/picotls
RUN git checkout 047c5fe20bb9ea91c1caded8977134f19681ec76 && git submodule init && git submodule update && OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake . && make

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations
RUN git clone https://github.com/private-octopus/picoquic.git && cd picoquic && git checkout bb67995f2d7c0e577c2c8788313c3b580d3df9a7 && /usr/bin/cmake . && make

WORKDIR /tmp/QUIC-FormalVerification

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONPATH="${PYTHONPATH}:/tmp/QUIC-FormalVerification/quic-implementations/aioquic/src"
ENV PYTHONUNBUFFERED=1

RUN cd webapp; pip3 install -e .

RUN python3 run_experiments.py --mode client --categories global_test --update_include_tls --timeout 180 --iter 1 --compile --implementations picoquic --initial_version 1 --alpn hq-interop || echo finished
```
Then you can run it with `docker run --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=1024g --rm --security-opt seccomp=unconfined --cap-add=NET_ADMIN -it <container-name>:latest`. 

Inside the container, you can see that the tester finishes properly, by following these steps:
1. open a second terminal
2. run in the first one: `PROOTPATH=/tmp/QUIC-FormalVerification PATH=/root/.local/bin:/root/.cargo/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin ZRTT_SSLKEYLOGFILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_tls_key.txt RETRY_TOKEN_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_retry_token.txt NEW_TOKEN_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_new_token.txt ENCRYPT_TICKET_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_encrypt_session_ticket.txt SESSION_TICKET_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_session_ticket_cb.txt SAVED_PACKET=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/saved_packet.txt initial_max_stream_id_bidi=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_id_bidi.txt active_connection_id_limit=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/active_connection_id_limit.txt initial_max_stream_data_bidi_local=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_bidi_local.txt initial_max_stream_data_bidi_remote=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_bidi_remote.txt initial_max_stream_data_uni=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_uni.txt initial_max_data=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_data.txt INITIAL_VERSION=29 TEST_TYPE=client TEST_IMPL=picoquic TEST_ALPN=hq-29 SSLKEYLOGFILE=/tmp/QUIC-FormalVerification/tls-keys/picoquic_key.log CNT=0 /tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/build/quic_client_test_max seed=649 the_cid=1 server_port=4443 iversion=29 server_addr=2130706433 modify_packets=false`
3. then run in the second one: `/tmp/QUIC-FormalVerification/quic-implementations/picoquic/picoquicdemo -n servername -a hq-29 -T /tmp/QUIC-FormalVerification/tickets/ticket.bin -v ff00001d -l - -D -L 127.0.0.1 4443`

But if you want to test it within shadow, you need to add the ip 11.0.0.1 with `ip a add 11.0.0.1 dev lo` (I don't know neither why the program can bind without problem outside of shadow nor why I have to create the IP address instead of shadow creating it). Then you can use this `shadow.yaml`:
```
general:
  # stop after 10 simulated seconds
  stop_time: 10s
  # old versions of cURL use a busy loop, so to avoid spinning in this busy
  # loop indefinitely, we add a system call latency to advance the simulated
  # time when running non-blocking system calls
  model_unblocked_syscall_latency: true

network:
  graph:
    # use a built-in network graph containing
    # a single vertex with a bandwidth of 1 Gbit
    type: 1_gbit_switch

hosts:
  # a host with the hostname 'server'
  server:
    network_node_id: 0
    ip_addr: "11.0.0.1"
    options:
      log_level: trace
    processes:
    - path: /tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/build/quic_client_test_max
      args: seed=649 the_cid=1 server_port=4443 iversion=29 server_addr=184549377 modify_packets=false
      environment: PROOTPATH=/tmp/QUIC-FormalVerification;PATH=/root/.local/bin:/root/.cargo/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin;ZRTT_SSLKEYLOGFILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_tls_key.txt;RETRY_TOKEN_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_retry_token.txt;NEW_TOKEN_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_new_token.txt;ENCRYPT_TICKET_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_encrypt_session_ticket.txt;SESSION_TICKET_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_session_ticket_cb.txt;SAVED_PACKET=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/saved_packet.txt;initial_max_stream_id_bidi=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_id_bidi.txt;active_connection_id_limit=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/active_connection_id_limit.txt;initial_max_stream_data_bidi_local=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_bidi_local.txt;initial_max_stream_data_bidi_remote=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_bidi_remote.txt;initial_max_stream_data_uni=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_uni.txt;initial_max_data=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_data.txt;INITIAL_VERSION=29;TEST_TYPE=client;TEST_IMPL=picoquic;TEST_ALPN=hq-29;SSLKEYLOGFILE=/tmp/QUIC-FormalVerification/tls-keys/picoquic_key.log;CNT=0
  client:
    network_node_id: 0
    quantity: 1
    ip_addr: "11.0.0.2"
    processes:
    - path: /tmp/QUIC-FormalVerification/quic-implementations/picoquic/picoquicdemo
      args: -n servername -a hq-29 -T /tmp/QUIC-FormalVerification/tickets/ticket.bin -v ff00001d -l - -D -L 11.0.0.1 4443
```

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
Ubuntu 18.04 in a Docker container
 - Kernel version: post the output of `uname -a`  
`Linux a01b99a8a444 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
Shadow v2.4.0-0-g264a05bf 2023-01-25--10:28:35
 - Which plug-ins you are using:  
None

**Additional context**
The tester is written in Ivy, then transpiled in C++, then compiled. It uses SMT solving (through z3) to generate possible packets and so it is heavy. I tried to compare performance profile of a normal run with a time-limited run inside shadow to see if the code was looping somewhere but the two profiles seemed quite similar.

**Comment by sporksmith** [comment]
Thanks for the detailed report!

> But if you want to test it within shadow, you need to add the ip 11.0.0.1 with ip a add 11.0.0.1 dev lo (I don't know neither why the program can bind without problem outside of shadow nor why I have to create the IP address instead of shadow creating it).

This makes me think that one of the managed programs is somehow escaping shadow's control. In version 2.4.0 it could happen if your programs use `exec`: https://github.com/shadow/shadow/issues/2718. The first release that has the fix is 3.0-pre though, which it might take a little work to update your simulation to run on. You could try cherry-picking the [fix](https://github.com/sporksmith/shadow/commit/42c46060ed915f736d7d0cf0c76687787fb3f70e), but all that does is have shadow reject the `execve` call instead of allowing it.

Another possibility is that something is accessing real network metadata via `/proc`, which we don't fully emulate. 

Could you try running the simulation with strace-logging enabled? You can pass the flag [`--strace-logging-mode=standard`](https://shadow.github.io/docs/guide/shadow_config_spec.html#experimentalstrace_logging_mode) to shadow. It should be relatively easy to tell from the generated `.strace` files if `exec` is being called and which `/proc` files are being accessed.

It'd also be helpful to have the full shadow stdout, or maybe just the `WARN` and `ERROR` lines if it's too large

**Comment by sporksmith** [comment]
```
  server:
...
  client:
...
      args: -n servername -a hq-29 -T /tmp/QUIC-FormalVerification/tickets/ticket.bin -v ff00001d -l - -D -L 11.0.0.1 4443
```

Should `servername` be `server`? Or maybe it doesn't matter since it looks like it's also passing the IP address?

**Comment by FlyearthR** [comment]
> Looking some more at your shadow config - is the server host actually running a server? The name of the binary looks like a client.

It is confusing: the server is called `quic_client_test_max` because it tests the client (here `picoquicdemo`).

> Could you try running the simulation with strace-logging enabled? You can pass the flag [--strace-logging-mode=standard](https://shadow.github.io/docs/guide/shadow_config_spec.html#experimentalstrace_logging_mode) to shadow. It should be relatively easy to tell from the generated .strace files if exec is being called and which /proc files are being accessed.

The generated .strace is empty for `quic_client_test_max` (the executable of interest) but correctly formed for `picoquicdemo`. If I strace the exectuable outside of shadow, it does not use `exec` and the only reference to `/proc` is in `readlink("/proc/self/exe")`.

> This makes me think that one of the managed programs is somehow escaping shadow's control.

It seems so: if I launch the client+server inside shadow AND the client outside of shadow, the server (launched within shadow) will communicate with the client outside of shadow.

> It'd also be helpful to have the full shadow stdout, or maybe just the WARN and ERROR lines if it's too large

Nothing much happens in the logs (I have to kill the simulation as it livelock otherwise). Logs can be accessed here: [shadow.log](https://github.com/shadow/shadow/files/11496574/shadow.log)

I am currently trying to build shadow 3.0-pre to test if it rejects an `execve` I would have missed.

**Comment by sporksmith** [comment]
Btw before spending too much more time debugging further it might still be worth bumping to shadow 3.0-pre, or even `HEAD`. Looking at your config, I think the only thing you'd need to update are:

* the `options` field is now named `host_options`
* the `environment` fields are now maps. e.g.

```
      environment: PROOTPATH=/tmp/QUIC-FormalVerification;PATH=/root/.local/bin:/root/.cargo/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin;ZRTT_SSLKEYLOGFILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_tls_key.txt;RETRY_TOKEN_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_retry_token.txt;NEW_TOKEN_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_new_token.txt;ENCRYPT_TICKET_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_encrypt_session_ticket.txt;SESSION_TICKET_FILE=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/last_session_ticket_cb.txt;SAVED_PACKET=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/saved_packet.txt;initial_max_stream_id_bidi=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_id_bidi.txt;active_connection_id_limit=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/active_connection_id_limit.txt;initial_max_stream_data_bidi_local=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_bidi_local.txt;initial_max_stream_data_bidi_remote=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_bidi_remote.txt;initial_max_stream_data_uni=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_stream_data_uni.txt;initial_max_data=/tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples/quic/initial_max_data.txt;INITIAL_VERSION=29;TEST_TYPE=client;TEST_IMPL=picoquic;TEST_ALPN=hq-29;SSLKEYLOGFILE=/tmp/QUIC-FormalVerification/tls-keys/picoquic_key.log;CNT=0
```

Would become:

```
environment:
    PROOTPATH: /tmp/QUIC-FormalVerification
    PATH: /root/.local/bin:/root/.cargo/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin
    ZRTT_SSLKEYLOGFILE: /tmp/QUIC-FormalVerification/QUIC-Ivy/doc/examples
...
```
