### ISSUE TITLE
Cannot read more bytes from TCP socket after `SHUT_RD`

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#3565]
In Linux, if you do a `SHUT_RD` on a TCP socket, you can still read remaining bytes in the inbuf, and any new bytes that arrive later. IIUC, the only thing that `SHUT_RD` does is that it prevents a `recv()` on the socket from blocking, instead immediately returning EOF.

The following simulation fails under shadow. On Linux, it works as expected.

```yaml
general:
  stop_time: 10 seconds
network:
  graph:
    type: 1_gbit_switch
hosts:
  server:
    network_node_id: 0
    processes:
    - path: python3
      expected_final_state: running
      args:
        - '-u'
        - '-c'
        - |
          import socket, time
          server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          server.bind(('0.0.0.0', 8080))
          server.listen(100)
          (s, _) = server.accept()
          server.close()
          print("Accepted socket")

          s.send(b'hello')
          time.sleep(2)
          s.send(b'world')

          # don't close the socket, we want to keep the socket open until the
          # end of the simulation so that closing the socket doesn't send a FIN
          time.sleep(1000)
  client:
    network_node_id: 0
    processes:
    - path: python3
      start_time: 100 ms
      args:
        - '-u'
        - '-c'
        - |
          import socket, time
          s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          s.connect(('server', 8080))
          print("Connected")

          s.shutdown(socket.SHUT_RD)

          # wait for the first message to arrive
          time.sleep(1)

          data = s.recv(5)
          print("First recv:", data)
          assert data == b'hello', str(data)

          # the server hasn't sent a FIN, but we read an EOF since there's currently no data
          assert s.recv(1) == b''

          # wait for the second message to arrive
          time.sleep(2)

          data = s.recv(5)
          print("Second recv:", data)
          assert data == b'world', str(data)

          # the server hasn't sent a FIN, but we read an EOF since there's currently no data
          assert s.recv(1) == b''
```

```text
Connected
First recv: b''
Traceback (most recent call last):
  File "<string>", line 13, in <module>
AssertionError: b''
```
