### ISSUE TITLE
FIN is never ACKed, leading to retransmitted FIN forever

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#3573]
I'm not clear on exactly what conditions cause this, but when a socket connects to a server and then both immediately close, one side won't ACK the other's FIN, so it will try to retransmit the FIN forever (with exponential backoff).

```yaml
general:
  stop_time: 3 minutes
  model_unblocked_syscall_latency: false
host_option_defaults:
  pcap_enabled: true
experimental:
  strace_logging_mode: standard
network:
  graph:
    type: gml
    inline: |
      graph [
        directed 0
        node [
          id 0
          host_bandwidth_up "1 Mbit"
          host_bandwidth_down "1 Mbit"
        ]
        edge [
          source 0
          target 0
          latency "20 ms"
          packet_loss 0.0
        ]
      ]
hosts:
  server:
    network_node_id: 0
    processes:
    - path: python3
      args:
        - '-u'
        - '-c'
        - |
          import socket, time
          server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          server.bind(('0.0.0.0', 8080))
          server.listen(100)
          (s, _) = server.accept()
          print("Accepted socket")

          # immediately close, which should send a FIN
          s.close()
  client:
    network_node_id: 0
    processes:
    - path: python3
      start_time: 100 ms
      args:
        - '-u'
        - '-c'
        - |
          import socket, time
          s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          s.connect(('server', 8080))
          print("Connected")

          # immediately close, which should send a FIN
          s.close()
```

```text
** Starting Shadow 3.2.0
** Shadow completed successfully
```

![Image](https://github.com/user-attachments/assets/78e870ad-6595-49d0-ab1a-ffb1ffb80161)
